export const LIB_TYPE_GENERATE = "type-generate";
export const TYPES_CACHE_DIRECTORY = "TYPES_CACHE_DIRECTORY";
export const TYPE_AGGREGATOR_BASE = "TYPE_AGGREGATOR_BASE";
export const TYPE_AGGREGATOR_KEY = "TYPE_AGGREGATOR_KEY";
