---
services:
  homeassistant:
    container_name: digital-alchemy_examples_homeassistant
    image: homeassistant/home-assistant:2023.2
    network_mode: "host"
    volumes:
      - ./config:/config
    restart: unless-stopped
