export enum CustomIcons {
  "c" = "\uE61E",
  "cpp" = "\uE61D",
  "electron" = "\uE62E",
  "elixir" = "\uE62D",
  "elm" = "\uE62C",
  "folder" = "\uE5FF",
  "folder_config" = "\uE5FC",
  "folder_git" = "\uE5FB",
  "folder_git_branch" = "\uE5FB",
  "folder_github" = "\uE5FD",
  "folder_npm" = "\uE5FA",
  "folder_open" = "\uE5FE",
  "go" = "\uE626",
  "msdos" = "\uE629",
  "vim" = "\uE62B",
  "windows" = "\uE62A",
}
