// <Configuration>
export const APPLICATION_IDENTIFIER = "APPLICATION_IDENTIFIER";
export const BASE_URL = "BASE_URL";
export const CRASH_REQUESTS_PER_SEC = "CRASH_REQUESTS_PER_SEC";
export const HOME_ASSISTANT_PACKAGE_FOLDER = "HOME_ASSISTANT_PACKAGE_FOLDER";
export const RENDER_TIMEOUT = "RENDER_TIMEOUT";
export const RETRY_INTERVAL = "RETRY_INTERVAL";
export const TALK_BACK_BASE_URL = "TALK_BACK_BASE_URL";
export const TOKEN = "TOKEN";
export const VERIFICATION_FILE = "VERIFICATION_FILE";
export const WARN_REQUESTS_PER_SEC = "WARN_REQUESTS_PER_SEC";
export const WEBSOCKET_URL = "WEBSOCKET_URL";
// </Configuration>

//
export const LIB_HOME_ASSISTANT = "push-entity";
export const DEFAULT_APPLICATION_IDENTIFIER = "({ application: 'THIS_VALUE' })";
