// <Configuration>
export const BASE_URL = "BASE_URL";
export const TALK_BACK_BASE_URL = "TALK_BACK_BASE_URL";
export const CRASH_REQUESTS_PER_SEC = "CRASH_REQUESTS_PER_SEC";
export const RENDER_TIMEOUT = "RENDER_TIMEOUT";
export const RETRY_INTERVAL = "RETRY_INTERVAL";
export const TOKEN = "TOKEN";
export const TALK_BACK_AUTH_HEADERS = "TALK_BACK_AUTH_HEADERS";
export const HEALTH_CHECK_INTERVAL = "HEALTH_CHECK_INTERVAL";
export const APPLICATION_IDENTIFIER = "APPLICATION_IDENTIFIER";
export const WARN_REQUESTS_PER_SEC = "WARN_REQUESTS_PER_SEC";
export const WEBSOCKET_URL = "WEBSOCKET_URL";
export const HOME_ASSISTANT_PACKAGE_FOLDER = "HOME_ASSISTANT_PACKAGE_FOLDER";
export const VERIFICATION_FILE = "VERIFICATION_FILE";
// </Configuration>

//
export const LIB_HOME_ASSISTANT = "home-assistant";
export const DEFAULT_APPLICATION_IDENTIFIER = "({ application: 'THIS_VALUE' })";
