export const DEFAULT_HEADER_FONT = "DEFAULT_HEADER_FONT";
export const SECONDARY_HEADER_FONT = "SECONDARY_HEADER_FONT";
export const PAGE_SIZE = "PAGE_SIZE";
export const HELP = "HELP";
export const LIB_TTY = Symbol("tty");
export const TABLE_RENDER_ROWS = "TABLE_RENDER_ROWS";
export const USE_FONTAWESOME_ICONS = "USE_FONTAWESOME_ICONS";
