export const LIB_PI_MATRIX_CLIENT = "pi-matrix-client";

export const UPDATE_INTERVAL = "UPDATE_INTERVAL";
export const RUNTIME_OPTIONS = "RUNTIME_OPTIONS";
export const ANIMATION_CACHE_DIRECTORY = "ANIMATION_CACHE_DIRECTORY";
export const DEFAULT_ANIMATION_INTERVAL = "DEFAULT_ANIMATION_INTERVAL";
export const BORDER_SPIN_LAYER_BOTTLENECK = "BORDER_SPIN_LAYER_BOTTLENECK";
export const FONTS_DIRECTORY = "FONTS_DIRECTORY";
